### ISSUE TITLE
[QUESTION] Assertions vs. Checks UI

### ISSUE THREAD

**Issue by agardnerIT** [kubeshop/tracetest#1033]
Given this test definition:

```
testDefinition:
- selector: span[name = "POST /pokemon/import"]
  assertions:
  - tracetest.span.duration <= 50ms
  - http.status_code = 200
  - tracetest.response.body contains 52
- selector: span[name = "queue.synchronizePokemon send"]
  assertions:
  - messaging.payload contains 52
```

I read this as "I have two `tests` or `checks`. In this first `test / check` I am asserting 3 things (ie. I have 3 assertions).

However the UI flips these definitions and calls the `assertions` above, `checks`. So according to the UI, I have `2 assertions`. Assertion 1 contains 3 checks and assertion 2 contains 1 check.

Can someone clarify which was round is correct?
