### ISSUE TITLE
[SPIKE] Chaining Tests

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#1040]
Based on this big boulder idea https://kubeshop.atlassian.net/wiki/spaces/KUBESHOP/pages/483622933/Big+Boulder+Ideas#%5BhardBreak%5DChaining-tests-NOW-FOR-DESIGN%2FSPECS-ONLY

We need a way for users to group and trigger sets of tests called Suites.

Each execution of a test can produce output that can be later used as input for the following test executions.
Users should be able to define this output and inputs while configuring the group of tests (Suite).

**Comment by mathnogueira** [comment]
This is my idea of how this should work. This is heavily inspired by #159 and #824.

## Problem
Today, as `Tracetest` can only execute the endpoint under test, it is impossible to do that setup because it requires extra endpoints to be called before the test itself is run. Thus, users have to rely on complex shell scripts to be able to run tests and reference information generated by other tests.

## Proposed Solution

### 1. Create a way of referencing data from another test run

This would allow a test to obtain information from another test run. A good example would be our own tests. When running a test using Tracetest, first we need to create it and then run it by referencing its `testID`. Instead of using shell script to get the `testID` and then use it in another test, we could use test chaining to do that operation for us:

```yaml
# create_test.yaml
name: Create a new test
trigger:
    type: http
    httpRequest:
        url: https://tracetest.io/api/tests
        method: POST
        body: '{ "name": "test name" }' # rest of the body is omitted
testDefinition:
    - selector: span[name = "Tracetest trigger"]
      assertions:
          - tracetest.response.status = 200 
      exports:
          - response: tracetest.response
```
```yaml
# run_test.yaml
name: Run test
requires:
  - createTest: ./create_test.yaml # name we are going to reference and the path to the test definition file
trigger:
    type: http
    httpRequest:
        url: https://tracetest.io/api/tests/{{ test.createTest.exports.response.id }}
        method: POST
testDefinition:
    - selector: span[name = "Tracetest trigger"]
    assertions:
        - tracetest.response.status = 200
        - tracetest.response.id = test.createTest.exports.response.id
```

**Comment by kdhamric** [comment]
Couple things we will need to consider:
- the selector in any test spec that has an export may match more than one particular span (ie if it match more than one span how can you know what value to set?). How should we handle this?
- we will need ways to set values based on parsing returned info (get a particular value from a XML based result, or a particular part of a JSON response, etc). How should we consider handling this?

**Comment by xoscar** [comment]
Hello team, I have prepared documentation for you that covers these topics:

1. Chaining of tests (Transactions).
2. Environment variables (Global).
3. Dynamic variables (Execution level).

The idea is to have something to shoot at while we think about the best solutions for each piece we want to build here.

You can find the initial documentation for core concepts and acceptance criteria here: https://kubeshop.atlassian.net/wiki/spaces/KUBESHOP/pages/596901910/No+more+BS+Plan

It also includes a link to the initial wireframes around how it might look when implemented.
https://balsamiq.cloud/sibxlh9/p3bbvoy

**Comment by xoscar** [comment]
@mathnogueira the solution I'm suggesting considers the outputs to be at the test level not at the assertion level, I think it is better that way because:

1. We don't have to create an assertion to have an output.
2. We also need to consider that there could be outputs from the trigger response (body, headers).

Here's some extra info showcased using an entity diagram:

```mermaid
erDiagram
    TEST {
        string id
        string make
        string model
    }
    OUTPUT {
        string id
        string attribute
        string selector
        string regex
        enum source
    }
    TEST ||--o{ TRANSACTION_TEST : has
    TRANSACTION {
        string id
        string status
        string name
    }
    TRANSACTION ||--o{ TRANSACTION_TEST : has
    TRANSACTION_TEST {
        string id
        string test_id
        string transaction_id
    }
    ENVIRONMENT {
        string id
        string name
        boolean isGlobal
    }
    ENVIRONMENT ||--o{ ENVIRONMENT_ENTRY: contained_by
    ENVIRONMENT_ENTRY {
        string id
        string environment_id
        string key
        string value
    }
```

Here we can see how the transactions co-relate with the tests and outputs.
And here's another one for snapshotting historic data like runs and dynamic environments.

```mermaid
erDiagram
    TEST_RUN {
        string transaction_run_id
    }
    TRANSACTION {
        string id
    }
    TRANSACTION_RUN {
        string id
        string transaction_id
        string dynamic_variables_id
    }
    TRANSACTION_RUN ||--o{ TEST_RUN : has
    TRANSACTION_RUN ||--o{ ENVIRONMENT : uses
    TRANSACTION ||--o{ TRANSACTION_RUN : outputs
    ENVIRONMENT {
        string id
        string name
        boolean isGlobal
    }
    ENVIRONMENT ||--o{ ENVIRONMENT_ENTRY: contained_by
    ENVIRONMENT_ENTRY {
        string id
        string environment_id
        string key
        string value
    }
```

**Comment by xoscar** [comment]
Here's some extra info around tests and transactions execution steps:

## Create Environment

```mermaid
sequenceDiagram
    User->>Frontend: Clicks create environment
    Frontend-->>User: Displays the form
    User ->>Frontend: Adds Name & Entries
    Frontend ->>Backend: Sends information
    Backend ->>Backend: Saves to DB
    Backend -->>Frontend: Ok
    Frontend -->> User: Ok
```

## Run test w/ environment side effect

```mermaid
sequenceDiagram
    User->>Frontend: Selects Environment
    Frontend->>Frontend: Updates Preferences
    Frontend-->>User: Ok
    User->>Frontend: Clicks Run
    Frontend->>Backend: Runs Test w/ Env id
    Backend->>Backend: Replaces env variables
    Backend->>Backend: Runs test
    Backend->>Backend: Processess outputs
    Backend->>Backend: Uptated env w/ output
    Backend-->>Frontend: Ok
    Frontend-->>User: Ok    
```

## Run Test w/o environment side effect

```mermaid
sequenceDiagram
    User->>Frontend: Selects Environment
    Frontend->>Frontend: Updates Preferences
    Frontend-->>User: Ok
    User->>Frontend: Clicks Run
    Frontend->>Backend: Runs Test w/ Env id
    Backend->>Backend: Replaces env variables
    Backend->>Backend: Runs test
    Backend-->>Frontend: Ok
    Frontend-->>User: Ok
```

## Run A Transaction

```mermaid
sequenceDiagram
    User->>Frontend: Selects Environment
    Frontend->>Frontend: Updates Preferences
    Frontend-->>User: Ok

    User->>Frontend: Runs transaction
    Frontend->>Backend: Send transaction info w/ env id
    Backend->>Backend: Copies Env to Dynamic envs
    loop For each test in transaction
        Backend-->>Frontend: Sends transaction status
        Frontend-->>User: Shows status
        Backend->>Backend: Replaces variables
        Backend->>Backend: Runs test
        Backend-->>Frontend: Sends test status
        Frontend-->>User: Shows status
        Backend->>Backend: Waits for trace
        Backend-->>Frontend: Sends test status
        Frontend-->>User: Shows status
        Backend->>Backend: Processing outputs
        Backend->>Backend: Hoists outputs to dynamic vars
        Backend-->>Frontend: Sends transaction status
        Frontend-->>User: Shows status
    end
    Backend->>Backend: Generates run snapshot
    Backend-->>Frontend: Returns transaction run info
    Backend-->>Frontend: Displays results    
```

**Comment by xoscar** [comment]
My suggested solution follows some of the patterns described here https://github.com/kubeshop/tracetest/issues/951
Where we have transactions that contain a list of tests that will be executed in a sequence.

An example would look like this:

```yaml
transaction:
  id: 97d63b49-bd51-4dda-be37-603faad0fa68
  name: Test Delete Cart
  tests:
    - ./tests/login.yaml # tests can reference local files
    - a3cdd83c-4f67-454a-bec3-fbdc9b0b0c67 # or by id
    # - ...
```

Where each of the tests will have its own set of outputs that during the transaction execution will be hoisted to the dynamic variables scoped just for that run.
Global environments should not be updated because we can face concurrency issues where multiple tests/transactions can be executed and might cause unwanted side effects.
