### ISSUE TITLE
Introduce the term 'test spec' in the API/CLI

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#1069]
**Context:** as part of v0.7 we want to improve the UX/UI around the Test Run Details page and we are including the new term `Test Spec` instead of `Assertions`. We want to have the same terminology in the API/CLI.

**AC1**
Update the test file to include the term `specs` instead of `testDefinition`
```yaml
name: my test
trigger:
   type: http
specs:
- selector: span[...]
  assertions:
  - tracetest.span.duration < 100ms
```

**AC2**
Update API references to match the new term `spec`
