### ISSUE TITLE
Improve trace pooling process

### ISSUE THREAD

**Issue by mathnogueira** [kubeshop/tracetest#1119]
## Problem
When Tracetest triggers a test and waits for the trace to be available, it executes a very simple condition to ensure the trace is complete. Today, the logic is very simple: if a trace is polled twice in a row and the number of spans didn't change, consider it complete. However, this is not true for long-running operations.

With the current implementation, if we had one test that takes a long time to generate the complete trace, we would have to adjust the pooling configuration to make sure to add enough time between polling executions to prevent false-positive complete traces. However, this would slow down all other tests executed by that tracetest instance.

### Enable the polling condition to be set at a test level

Instead of hardcoding the condition, we could let a test define when a trace is complete and can be asserted. If this is not configured in the test, we would use the default implementation.

#### Test with default polling configuration
When the `polling` object is not defined, the default polling strategy would be by counting the number of spans and check if they are equal. If they are equal in two subsequent polling executions, the trace is marked as complete.

```yaml
name: My test
trigger:
    # how to trigger the test

spec:
    # assertions
```

#### Test using the same default polling strategy, but with different parameter

```yaml
name: My test
trigger:
    # how to trigger the test

polling:
    strategy: sameSpanCount
    sameSpanCount:
        executions: 3 # if the number of spans is the same in 3 subsequent executions, the trace is marked as complete

spec:
    # assertions
```

#### Test using an assertion to stop polling

```yaml
# slow-test.yaml
name: My slow test
trigger:
   # how to trigger the test

polling:
   # polling would only stop when a span named "insert pokemon into database" is present in the trace
   strategy: assert
   assert:
       selector: span[name = "insert pokemon into database"
       assertion: tracetest.selected_spans.count = 1

spec:
    # assertions
```

**Comment by kdhamric** [comment]
On the polling solution, should you be able to specify the polling interval in addition to the max number of polls?

On the solution where you wait for a particular span, should we add a 'maximum time to wait'?

**Comment by mathnogueira** [comment]
Today we have that in tracetest's global configuration:

```yaml
pollingConfig:
    timeout: 10m
    retryDelay: 5s
```

Maybe it makes sense to have that as the default configuration and allow tests to override that information

**Comment by mathnogueira** [comment]
@schoren can you add your proposal here?

**Comment by kdhamric** [comment]
Couple of comments:

It would be good if the config info globally had the same (or similar) structure to the per test override. Labeling the strategy / strategy type makes sense - we have identified a 'sameSpanCount' and 'assert' - there may be others in the future.

I could see a case for defining some common polling scenarios at a global level... but this might be (is?) overkill.

I might tend to have this at a global level:

polling:
   default: fastTest
   options:
    - longRunningTest:
        name: Long running test
        strategy: sameSpanCount
        executions: 3 # if the number of spans is the same in 3 subsequent executions, the trace is marked as complete
        retryDelay: 60s
        timeout: 120m
    - mediumTest:
        name: Medium length test (1 to 10 minutes)
        strategy: sameSpanCount
        executions: 3 # if the number of spans is the same in 3 subsequent executions, the trace is marked as complete
        retryDelay: 15s
        timeout: 10m
    - fastTest:
        name: Fast test (less than a minute)
        default: true
        strategy: sameSpanCount
        executions: 3 # if the number of spans is the same in 3 subsequent executions, the trace is marked as complete
        retryDelay: 2s
        timeout: 1m
    
 In a test level, I would have the exact same structure.  
 
 polling:
   default: fastTest
   
 or, if they have set a custom one:
 
 polling:
   default: custom
   options:
    - custom:
        name: check for db span at end
        strategy: assert
        selector: span[name = "insert pokemon into database"
        assertion: tracetest.selected_spans.count = 1
        retryDelay: 10s
        timeout: 10m
        
 We need to consider how this would appear in UI also @olha23 once we get consensus on what to implement (the above may be too much)

**Comment by mathnogueira** [comment]
I like your suggestion, @kdhamric. Maybe we could have `polling profiles`:

```yaml
polling:
   defaultProfile: fastTest
   profiles:
    - longRunningTest:
        name: Long running test
        strategy: sameSpanCount
        executions: 3 # if the number of spans is the same in 3 subsequent executions, the trace is marked as complete
        retryDelay: 60s
        timeout: 120m
    - mediumTest:
        name: Medium length test (1 to 10 minutes)
        strategy: sameSpanCount
        executions: 3 # if the number of spans is the same in 3 subsequent executions, the trace is marked as complete
        retryDelay: 15s
        timeout: 10m
    - fastTest:
        name: Fast test (less than a minute)
        default: true
        strategy: sameSpanCount
        executions: 3 # if the number of spans is the same in 3 subsequent executions, the trace is marked as complete
        retryDelay: 2s
        timeout: 1m
```

```yaml
polling:
  profile: fastTest
```

**Comment by olha23** [comment]
@kdhamric from UI perspective we should allow users to define the number of times a trace can be polled before being marked as “complete” in the test configuration?

**Comment by kdhamric** [comment]
@olha23 Yes, we should. Eventually, we will allow people to define multiple profiles as given above. For that, they would need to be able to specify all the fields: name, strategy, executions, retry delay, and timeout. I am not sure when we will tackle this work - it would not hurt to begin to mock some of it.

**Comment by danielbdias** [comment]
Team, giving my +1 here since our polling config is affecting integrations with OTel Collector. I like the idea of having global polling configs (like `profiles`), and I believe that we could think about them in a similar way that k8s deals with probes ([k8s API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#probe-v1-core)).

I believe that we could add one more option: `initialDelaySeconds` and change `executions` to `stopThreshold`.

```yaml
polling:
   defaultProfile: fastTest
   profiles:
    - somePolling:
        name: Some polling
        default: true
        strategy: sameSpanCount
        stopThreshold: 3 # if our strategy signalizes that we should stop three times in a row, 
                         # we should stop polling
        initialDelay: 1s
        retryDelay: 2s
        timeout: 1m
```

With that, we can model quick pollings, like API calls:

```yaml
   profiles:
    - apiPolling:
        name: API Polling
        strategy: sameSpanCount
        stopThreshold: 3 # if our strategy signalizes that we should stop three times in a row, 
                         # we should stop polling
        initialDelay: 0s
        retryDelay: 2s
        timeout: 1m
```

And longer pollings, like async ones:
```yaml
   profiles:
    - asyncContinuousPolling:
        name: Async continuous Polling
        strategy: sameSpanCount
        stopThreshold: 3 # if our strategy signalizes that we should stop three times in a row, 
                         # we should stop polling
        initialDelay: 0s
        retryDelay: 10s
        timeout: 10m
    - fireAndForgetPolling: # for cases where there is a delay between 
                            # starting the action and executing the action
        name: Async continuous Polling
        strategy: sameSpanCount
        stopThreshold: 5 # if our strategy signalizes that we should stop three times in a row, 
                         # we should stop polling
        initialDelay: 1m
        retryDelay: 30s
        timeout: 10m
```
