### ISSUE TITLE
Support for "internal variables" in tests

### ISSUE THREAD

**Issue by schoren** [kubeshop/tracetest#1379]
Example case:

I am testing a create product flow. It starts with an API call, which triggers a DB insert. The new ID is then passed to some other internal services. I want to assert that all traces after the DB insert include that new ID.

Our current implementation does not allow for this, because within an assertion, you can only reference attributes in the matching span:

```yaml
id: VZvc1g44g
name: Test Create
trigger: # ...
specs:
# all spans should have the created ID
- selector: span[]
  assertions:
    - attr:myapp.created_id = ? # whatever we use here, will reference the current span
```

Proposals:

## Use outputs internally.

If the outputs are processed before the specs, we could do something like this:

```yaml
id: VZvc1g44g
name: Test Create
trigger: # ...

outputs:
- name: createdID
  selector: span[name="db insert']
  value: attr:myapp.created_id

specs:
# all spans should have the created ID
- selector: span[]
  assertions:
    - attr:myapp.created_id = ${env:createdID}
```

This would work fine on isolation, but would create (and maybe even override) an Environment Variable when running in the context of a transaction.

## Add a `variables` section

Variables would work as `outputs` scoped to a test. The difference is that instead of being exported to the env when running in a transaction, these would only live within a test.

```yaml
id: VZvc1g44g
name: Test Create
trigger: # ...

outputs:
- name: THIS_IS_EXPORTED
  selector: span[name="root']
  value: attr:myapp.some_value

variables:
- name: createdID # this is not exported
  selector: span[name="db insert']
  value: attr:myapp.created_id

specs:
# all spans should have the created ID
- selector: span[]
  assertions:
    - attr:myapp.created_id = ${var:createdID}
    - attr:myapp.other_attr = ${env:THIS_IS_EXPORTED} # exported could be referenced here too
```

Other possible implementations:

### Exportable variables

Replace `outputs` with `variables`, add an `export` bool flag:

```yaml
variables:
- name: createdID
  export: false # could be the default
  selector: span[name="db insert']
  value: attr:myapp.created_id
- name: THIS_IS_EXPORTED
  export: true
  selector: span[name="root']
  value: attr:myapp.some_value


specs:
# all spans should have the created ID
- selector: span[]
  assertions:
    - attr:myapp.created_id = ${var:createdID}
    # exported variables needs to be referenced via `env` to be consistent with consuming exported vars from other tests
    - attr:myapp.other_attr = ${env:THIS_IS_EXPORTED} 
```

### Outputs are reference to variables

This is similar to terraform's module outputs. In terraform, a module can define all the internal variables it wants, but only the defined `outputs` can be referenced from other modules.

In our case, `outputs` values would be merged with the env variables for the next transaction.

```yaml
variables:
- name: createdID
  selector: span[name="db insert']
  value: attr:myapp.created_id
- name: someValue
  selector: span[name="root']
  value: attr:myapp.some_value

outputs:
- name: THIS_IS_EXPORTED
  variable: someValue

specs:
# all spans should have the created ID
- selector: span[]
  assertions:
    - attr:myapp.created_id = ${var:createdID}
    # exported variables needs to be referenced via `env` to be consistent with consuming exported vars from other tests
    - attr:myapp.other_attr = ${env:THIS_IS_EXPORTED} 
```

**Comment by mathnogueira** [comment]
Now that I'm looking at all possibilities. It would make sense to start with the `Add a variables section`. It seems cleaner, and later, if needed we can add a way of reducing the duplication.

Just one question: what do you think about referencing outputs as:

```yaml
specs:
# all spans should have the created ID
- selector: span[]
  assertions:
    - attr:myapp.created_id = ${var:createdID}
    # exported variables needs to be referenced via `env` to be consistent with consuming exported vars from other tests
    - attr:myapp.other_attr = ${output:THIS_IS_EXPORTED} 
```

My understanding is that the `env:` will be used to reference environment variables when we support them.

**Comment by schoren** [comment]
I'm not sure about adding the `output:` prefix. I get confused by the fact that an `env` can come from any external source, but `output` can only be internal. I'm still trying to internalize that concept

If we add the `output` prefix so a test can reference an output as if it was a variable,then outputs just become exported variables, so wouldn't it make more sense to treat everything as a `variable` and add an `export: bool` flag? (aka `Exportable variables`). For this to work, outputs would have to be processed before assertions (same as variables)

It would be different if we decided to process outputs after assertions (not sure if we want to, its pro/cons, etc), then referencing outputs would have no meaning, since they would be always be empty at the time of assertions.
I think it would be a little weird and counter intuitive to process outputs before even processing assertions, but I don't know if it's really important.

**Comment by mathnogueira** [comment]
if we have variables, does it make sense to allow outputs to be referenced in the test that they are run? We could just run:

1. pick a test to run
   1. resolve variables
   2. execute assertions
   3. resolve outputs
2. set outputs as `env` variables for tests to be executed next
3. pick next test to run

**Comment by schoren** [comment]
I think that flow makes the most sense of any options. In that case, your tests can only reference internal variables or env vars. A definition would look like this:

```yaml
id: VZvc1g44g
name: Test Create
trigger: # ...

variables:
- name: createdID # this is not exported
  selector: span[name="db insert']
  value: attr:myapp.created_id

specs:
# all spans should have the created ID
- selector: span[]
  assertions:
    - attr:myapp.created_id = ${var:createdID}
    # - attr:myapp.other_attr = ${env:THIS_IS_EXPORTED} # not valid, this value is not set until end of test

outputs:
- name: THIS_IS_EXPORTED
  selector: span[name="root']
  value: attr:myapp.some_value

# allow using vars here too
- name: CREATED_ID
  value: var:createdID 
```

Should we allow the last output syntax? It enables value reusing between vars/outputs, not sure if it has any drawbacks.
