### ISSUE TITLE
Enable tests to have a setup phase before executing the test

### ISSUE THREAD

**Issue by mathnogueira** [kubeshop/tracetest#159]
## Context
When writing integration tests, it is common to have some setup phase where you create all the resources the test will need in order to work. A good example of that would be an integration test for an update endpoint. Before we can update anything, we have to create the resource and ensure that it exists and can be updated.

## How we would do it without tracetest
For simplicity, I'm omitting implementation details and error handling.

```golang
func TestUserUpdate(t *testing.T) {
    // Setup phase
    user, err := createNewUser()
    // End of setup phase

    new_user_data = models.User{
        Name: "John Doe",    
    }
    updated_user, err := updateNewUser(user.ID, new_user_data)
    // Assertions
    // ...
}
```

## Problem
Today, as `tracetest` can only executes the endpoint under test, it is impossible to do that setup because it require extra endpoints to be called before the test itself is run.

## Possible solution
I'm thinking about enabling users to create user-defined setup steps. Those steps would be as simple as sending a request to an endpoint, retrieving its response, validate if its `status_code` is the one expected and store the response body to be referenced later. I'll use `YAML` to represent what those steps would look like.

**Note**: I've added a lot of notes as comments of this `YAML` file. It is worth to read them.

```yml
# create-user-step.yml
createNewUser:
    type: setup-step
    name: create a new user
    execution:
        # Thinking about the future here. We might want to have multiple ways of executing a setup step
        # Maybe we end up with "http", "grpc" and "queue" types in the future
        type: http
        endpoint: https://my-api.com/api/users
        method: POST
        headers:
            - name: Authorization
              value: Bearer some-token
            - name: X-my-custom-header
              value: some random value
        # To ensure that setup steps always work, we might have to implement some way of generating data for
        # those requests. Maybe having something like ${generate: fullName} and ${generate: email}.
        # Postman has this feature implemented. 
        # Reference: https://learning.postman.com/docs/writing-scripts/script-references/variables-list/
        body: '{"name": "John Doe", "email": "john.doe@company.com"}'
        expectedStatusCode: 201



# create-group-step.yml
createNewGroup:
    type: setup-step
    name: create a new group
    execution:
        type: http
        endpoint: https://my-api.com/api/groups
        method: POST
        body: '{"name": "fake-employees"}'
        expectedStatusCode: 201



# assign-user-to-group-step.yml
assignUserToGroup:
    type: setup-step
    name: assign user to group
    execution:
        type: http
        # I'm thinking about using the same approach used by terraform here. 
        # As soon as a step executes, you can fetch values obtained from its execution 
        # and use in other resource. So, here I'm getting the response obtained by
        # the createNewGroup step and using the attribute groupId from the response body.
        endpoint: https://my-api.com/api/groups/${createNewGroup.response.groupId}/users
        method: POST
        # Same thing here. I'm getting the value of userId from the response body obtained when createNewUser
        # executed the request.       
        body: '{"userId": "${createNewUser.response.userId}"}'
        expectedStatusCode: 200



# test-remove-user-from-group.yml
testRemoveUserFromGroup:
    type: test
    name: remove user from group
    setup:
        # The setup steps would be executed sequentially in the order declared here
        # After the last setup step is executed, we run the test. 
        - createNewGroup
        - createNewUser
        - assignUserToGroup
    execution:
        type: http
        # Tests also need to be able to reference values obtained from setup steps
        endpoint: https://my-api.com/api/groups/${createNewGroup.response.groupId}/users/${createNewUser.response.userId}
        method: DELETE
     assertions: 
         - name: HTTP
           property: http.status_code
           comparison: equals
           value: 200
         - name: HTTP POST /user/verify
           property: http.response.body
           comparison: contains
           value: ok
         - name: HTTP POST /user/verify
           property: traceDurationMs
           comparison: less-than
           value: 1000
```

For this to work there are some rules:
1. Resource names MUST be unique. Even when both resources are of different types.
2. If a setup step fails, the test fails

## Technical details
I'll leave those for later. I want some feedback on this before going deep on implementation details.

**Comment by marktheunissen** [comment]
Hi @mathnogueira we're evaluating Trace Test and would definitely need this feature to replace our existing test suite. 

The high level design here looks good! Could we also add a `tearDown` to complement the `setup`? The tear down phase is often responsible for deleting the created test data.

It might be useful to do a similar thing that Go's subtests do: you can define some setup and teardown steps that are always executed at least once if any of the subtests are executed: see ["Setup and Tear-down"](https://go.dev/blog/subtests)

Are there any workarounds that people are using at the moment?

**Comment by mathnogueira** [comment]
Hey @marktheunissen! We are working on [transactions](https://github.com/kubeshop/tracetest/issues/951) for version `v0.8` and it should allow you to run tests sequentially. We won't have a `setup` or `tear-down` step in that version, but you could use tests as a workaround to achieve the same result:

```yaml
name: Purchase item test
steps:
  # setup
  - tests/create-user.yaml
  - tests/create-product.yaml
  # test
  - tests/purchase-product.yaml
  # teardown
  - tests/delete-product.yaml
  - tests/delete-user.yaml
```

It will also allow you to cross-reference values from previous tests, so you will be able to use the `userID` and `productID` obtained from the tests that create them and inject that value into your `purchase-product.yaml`.

We expect that to be out in a couple of weeks. Let me know if this helps you and your team.
