### ISSUE TITLE
[EPIC][In-App Config] Configure trace data stores independent of install process

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1612]
Currently, the Tracetest server install command walks a user through a series of questions to setup the connection to the trace data store. This includes asking what type of trace data store (Jaeger, OpenSearch, SignalFX, etc) and then questions related to each. If all are answered properly, the system will work. If not, you either need to reinstall or manually change the server config file.

We want to move the initial configuration to be allowed later in the process and to be 'changeable' without restarting the server. This would allow a new user to do a straightforward install with little thought or fact finding beforehand. When they launch the tool, they would be prompted to setup a connection to the backend trace data store. This would ease the user journey - they would successfully install Tracetest as it would have very little information needed for the install to work. When adding the datastore, we could allow them to enter it and test it, with a UI guiding the journey.

The trace data store wizard should:
  - ask the type of trace data store. The sequence of questions asked based on this will be different
  - ask the specific questions based on the data store (url, auth info, etc)
  - do a test against the trace data store
  
In the configuration screen you should be able to see the trace data store configuration, test the configuration, and alter the configuration.

### Tickets for this epic

- [x] #1638
- [x] #1625
- [x] #1622
- [x] #1627 
- [x] #1640
- [x] #1628
- [x] #1629
- [x] #1630
- [x] #1621 
- [x] #1654
- [x] #1656 
- [x] #1657 
- [x] #1679 
- [x] #1686 
- [x] #1687
- [x] #1688
- [x] #1706
- [x] #1693
- [x] #1703
- [x] #1700
- [x] #1702
- [x] #1704

### List of bugs/improvements

- [x] #1739
- [x] #1732 
- [x] #1751

**Comment by mathnogueira** [comment]
### Allow a trace data store to be configured via the CLI after install

I was thinking about enabling configs to be added/deleted with:

**Add**
```sh
tracetest server data-source apply -f data-source.yaml
```
```yaml
type: DataStore
spec:
  # just like environments, data store slugs would be named all lowercase with dashes (-) instead of spaces.
  # so it would become "production-jaeger"
  name: Production Jaeger
  type: jaeger
  jaeger:
    url: prod.jaeger.my-company.com
    insecure: true
```

**Delete**

```sh
tracetest server data-source delete <data-source-slug>
```
