### ISSUE TITLE
[In-App Config] CLI Setup

### ISSUE THREAD

**Issue by mathnogueira** [kubeshop/tracetest#1621]
We need a way of enabling the CLI to configure a data store to be used by Tracetest.

I was thinking about enabling configs to be added/deleted with:

**Add**
```sh
tracetest server data-store apply -f data-source.yaml
```
```yaml
type: DataStore
spec:
  # just like environments, data store slugs would be named all lowercase with dashes (-) instead of spaces.
  # so it would become "production-jaeger"
  name: Production Jaeger
  type: jaeger
  jaeger:
    url: prod.jaeger.my-company.com
    insecure: true
```

**Delete**

```sh
tracetest server data-store delete <data-source-slug>
```

_Originally posted by @mathnogueira in https://github.com/kubeshop/tracetest/issues/1612#issuecomment-1334330365_
