### ISSUE TITLE
[docs] Update creating data stores in Configuration

### ISSUE THREAD

**Issue by adnanrahic** [kubeshop/tracetest#1811]
Existing data store configs use the full Tracetest config file. Re-write this to use WebUI and CLI for configuring the data store.

E.g.
https://docs.tracetest.io/configuration/connecting-to-data-stores/opentelemetry-collector

Replace with guide to use:
```
type: DataStore
spec:
  name: Opentelemetry Collector pipeline
  type: otlp
  isDefault: true
```
```
tracetest datastore apply -f my/data-store/file/location.yaml
```

Todo:

- [x] Apply to all data store configs
