### ISSUE TITLE
Elasticsearch (Elastic APM) connection UI to allow skipping TLS cert verification

### ISSUE THREAD

**Issue by michaelhyatt** [kubeshop/tracetest#1817]
I am trying to figure out the format for Elastic APM testdb in `tracetest-config.yml`. By the looks of it, it still relies on `opensearch` config items. It will be good to create a separate Elasticsearch configuration to avoid users confusing it with OpenSearch. It can also be useful to add additional configuration options to it, first and foremost the option of TLS verification to be set to none. A lot of the test environments are set with TLS, however, TLS validation can be skipped in non-prod environments.

Elasticsearch Go client example:
```go
es := elasticsearch.NewClient(elasticsearch.NewTransport(
...
  estransport.Transport.WithInsecureSkipVerify(true),
...
)
```

`tracetest-config.yml` `telemetry` element example:
```yaml
telemetry:
  dataStores:
    elasticsearch:
      type: elasticsearch
      elasticsearch:
        addresses:
          - https://es01:9200
        username: elastic
        password: changeme
        ssl:
          verification_mode: none
        index: apm-*
```

You can use this as an example of yaml config to Elasticsearch:
https://www.elastic.co/guide/en/beats/filebeat/current/elasticsearch-output.html

Continuation of #1777

**Comment by jorgeepc** [comment]
Hey @michaelhyatt thanks for your contribution. We merged the support for `Elasticsearch` (APM) as part of #1777, however it's not released yet (the team is also working in the documentation). If you are using main you can give it a try.

We support the new ElasticSearch data store in our `tracetest-config.yml`, it should be something like this:

```yaml
telemetry:
  dataStores:
    elasticApm:
      type: elasticApm
      elasticApm:
        addresses:
          - https://es01:9200
        username: elastic
        password: changeme
        index: apm-*
        certificate: ....
```

Please let us know if you find any issue with this.

**Comment by michaelhyatt** [comment]
Thanks, @jorgeepc

My ask was probably a bit messy, apologies. I am after an additional option (a checkbox) that can turn off TSL certificate validation. It is useful to have it switched off for non-prod deployments as a quick workaround to get the connection working rather than uploading it through the UI. The checkbox value can be passed to Elasticsearch go client through `WithInsecureSkipVerify(true)`.

Hope it makes sense.

**Comment by adnanrahic** [comment]
Hey @michaelhyatt! We just had a discussion and agree with you it would be awesome to have the TSL cert validation optional. You're totally on point. 

The plan is to start working on it this week. We'll keep you in the loop on progress. 🙌

**Comment by jorgeepc** [comment]
Hey @michaelhyatt we merged a PR with support for `insecureSkipVerify` for `ElasticSearch`/`OpenSearch`. If you want to try it you can use our main branch for now.

You can configure the data store directly in the UI and use the `Enable TLS but not verify the certificate` checkbox:

<img width="1490" alt="Screenshot 2023-01-19 at 14 52 54" src="https://user-images.githubusercontent.com/3879892/213545966-abed931f-80be-4838-be03-8e0a82934f51.png">

If you want to use the `tracetest-config.yml` file for the initial setup of the data store, you can add the following:

```yaml
    elasticapm:
      type: elasticapm
      elasticapm:
        addresses:
          - https://localhost:9200
        username: elastic
        password: changeme
        index: traces-apm-*
        insecureSkipVerify: true
```

Please let us know if you have any question.
