### ISSUE TITLE
conditions on assertions

### ISSUE THREAD

**Issue by mathnogueira** [kubeshop/tracetest#1914]
**Is your feature request related to a problem? Please describe.**
Imagine the following trace:
```
Get User
├─ Get user from cache
│  ├─ Redis GET
├─ Get user from DB
│  ├─ Postgres SELECT
```
How can I test the following scenario?
1. I cannot have a Get user from DB if I got a cache hit in Get user from cache
2. I must have a Get user from DB if I got a cache miss in Get user from cache

**Describe the solution you'd like**
To be able to define conditions that have to be met for an assertion to be executed.

Example:
```yaml
type: Test
spec:
  name: Check if cache works
  trigger:
    type: http
    ...
  outputs:
    - name: USER_CACHE_HIT
      selector: span[name = "Get user from cache"]
      value: attr:db.result
  specs:
    # If we got a cache miss, "Get user from DB" should exist in trace
    - selector: span[name = "Get user from DB"]
      condition: env:USER_CACHE_HIT = "null"
      assertions:
        - tracetest.selected_spans.count = 1
    
    # If it's a cache hit, app should not get data from db
    - selector: span[name = "GET user from DB"]
      condition: env:USER_CACHE_HIT != "null"
      assertions:
        - tracetest.selected_spans.count = 0
```
