### ISSUE TITLE
Create a telemetry, demo, polling profiles page in the docs (ken)

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#2171]
- Adding resource specs for yaml definitions (CLI)
- Adding Web UI documentation for the new settings options

**Comment by xoscar** [comment]
@xoscar to add information on how to use the new CLI commands for resources

**Comment by xoscar** [comment]
To use the unreleased tracetest CLI version, download the repo, pull the latest main branch, and move to the CLI directory.

From there you can run the commands using the following:
```bash
go run main.go <command>
```

You'll need to go to be installed on your local machine.

Here's the info per resource

### Config

**Spec:**

```yaml
type: Config
spec:
  analyticsEnabled: false
  id: current
  name: Config
```

**Commands:**

- get: `go run main.go get config`
- apply: `go run main.go apply config --file <file_path>`
- export: `go run main.go export config --file <file_path>`

### Polling Profile

**Spec:**

```yaml
type: PollingProfile
spec:
    default: false
    id: default
    name: default
    periodic:
      retryDelay: 500ms
      timeout: 10s
    strategy: periodic
```

**Commands:**

- get: `go run main.go get pollinprofile --id <id>`
- list: `go run main.go list pollingprofile --sortBy name --sortDirection asc --take 20 --skip 0`
- apply: `go run main.go apply pollinprofile --file <file_path>`
- export: `go run main.go export pollinprofile --id <id> --file <file_path>`
- delete: `go run main.go delete pollinprofile --id <id>`

### Demo

**Spec:**

```yaml
type: Demo
spec:
    enabled: true
    id: pokeshop
    name: pokeshop
    opentelemetryStore: {}
    pokeshop:
      grpcEndpoint: localhost:8082
      httpEndpoint: http://localhost:8081
    type: pokeshop

type: Demo
spec:
    enabled: true
    id: opentelemetrystore
    name: opentelemetryStore
    opentelemetryStore:
      cartEndpoint: http://localhost:8081
      checkoutEndpoint: http://localhost:8081
      frontendEndpoint: http://localhost:8081
      productCatalogEndpoint: http://localhost:8081
    pokeshop: {}
    type: opentelemetryStore
```

**Commands:**

- get: `go run main.go get demo --id <id>`
- list: `go run main.go list demo --sortBy name --sortDirection asc --take 20 --skip 0`
- apply: `go run main.go apply demo --file <file_path>`
- export: `go run main.go export demo --id <id> --file <file_path>`
- delete: `go run main.go delete demo --id <id>`


To write the final documentation change `go run main.go` for `tracetest`
