### ISSUE TITLE
Examples are not showing for the OTel Store demo

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#2191]
The examples for the OTel store are not showing in beta, even when the OTel Store demo is enabled in the settings page.

To reproduce, turn off the Pokemon demo in settings, demo - turn off 'enable Pokemon'. Then, process this file to turn on the OTel Store demo:

```
type: Demo
spec:
  type: opentelemetryStore
  enabled: true
  id: opentelemetrystore
  name: opentelemetryStore
  opentelemetryStore:
    cartEndpoint: http://otel-cartservice.otel-demo:7070
    checkoutEndpoint: http://otel-checkoutservice.otel-demo:5050
    frontendEndpoint: http://otel-frontend.otel-demo:8084
    productCatalogEndpoint: http://otel-productcatalogservice.otel-demo:3550
  pokeshop: {}
```
  
  With this command:
  'tracetest apply demo --file yourfile.yaml'
  
  Go to create a new test, and pick a trigger type of http or gRPC - you should see a drop down that says 'Choose example', but it is not showing.
