### ISSUE TITLE
`test run` command is ignoring environment variables file defined by the argument `-e`

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#2481]
**Describe the bug**

When running a test using `tracetest run test` command, when can pass a `-e` argument with an environment definition file. Today, on the version `0.11.6` the Tracetest CLI is ignoring this file and is not providing any output about that:

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/12397879/236069545-9c7aa692-ad05-4536-a53d-a448f23e0bad.png">

Example of test and environment file:

```yaml
type: Test
spec:
  name: Add product to the cart
  description: Add a selected product to user shopping cart
  trigger:
    type: http
    httpRequest:
      url: ${env:CART_API_URL}
      method: POST
      headers:
      - key: Content-Type
        value: application/json
      body: '{"item":{"productId":"${env:PRODUCT_ID}","quantity":1},"userId":"${env:USER_ID}"}'
  specs:
  - selector: span[tracetest.span.type="http" name="hipstershop.CartService/AddItem"]
    name: "Checking if the correct ProductID was sent"
    assertions:
    - attr:app.product.id = "${env:PRODUCT_ID}"
  - selector: span[tracetest.span.type="database" name="HMSET" db.system="redis" db.redis.database_index="0"]
    name: "Checking if the product was persisted correctly on the shopping cart"
    assertions:
    - attr:tracetest.selected_spans.count >= 1
```

Env file:
```yaml
type: Environment
spec:
  id: user-buying-products-env
  name: User buying Products - Env
  description: Environment for the process - "User buying products"
  values:
  - key: CART_API_URL
    value: http://frontend:8080/api/cart
  - key: CHECKOUT_API_URL
    value: http://frontend:8080/api/checkout
  - key: PRODUCT_ID
    value: OLJCESPC7Z
  - key: USER_ID
    value: 2491f868-88f1-4345-8836-d5d8511a9f83
```
