### ISSUE TITLE
DAPR configuration

### ISSUE THREAD

**Issue by BartNetJS** [kubeshop/tracetest#2502]
I try to setup my [dapr ](https://docs.dapr.io/operations/monitoring/tracing/setup-tracing/) environment to write traces to tracetest.
But in the logs i got:

Post "http://tracetest.tracetest.svc.cluster.local:4317/v1/traces": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x06\x04\x00\x00\x00\x00\x00\x00\x05\x00\x00@\x00"

My dapr config file:

apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-config
  namespace: {{ .Values.namespace }}
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin:9411/api/v2/spans"
    otel:
      endpointAddress: "tracetest.tracetest.svc.cluster.local:4317"
      protocol: "http"
      isSecure: false

It is not clear to me what I'm configuring wrong.

I also checked the OpenTelemetry config section in tracetest and tried a 'test Connection', but then i got:

"No Automated Test
Since the OpenTelemetry Collector sends traces to Tracetest, there is no automated test. Once you have configured your OpenTelemetry Collector to send Tracetest spans to Tracetest, try running a Tracetest test against your application under test."

**Comment by mathnogueira** [comment]
Hey @BartNetJS. I'll check the issue this afternoon. Thanks for reporting it!

**Comment by mathnogueira** [comment]
Oh I think what's happening. You are using the wrong port. `4317` is the gRPC port. You should point to port `4318` instead.

So you are getting a gRPC response instead of a HTTP response and this is breaking the integration. Try using the grpc protocol or change the port you are using in your `spec.tracing.otel.endpointAddress` to 4318:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
    name: dapr-config
namespace: {{ .Values.namespace }}
spec:
    tracing:
        samplingRate: "1"
        zipkin:
            endpointAddress: "http://zipkin:9411/api/v2/spans"
        otel:
            endpointAddress: "tracetest.tracetest.svc.cluster.local:4318"
            protocol: "http"
            isSecure: false
```
