### ISSUE TITLE
InlineData for tests

### ISSUE THREAD

**Issue by BartNetJS** [kubeshop/tracetest#2526]
In xunit you can define [InlineData ](https://andrewlock.net/creating-parameterised-tests-in-xunit-with-inlinedata-classdata-and-memberdata/#using-the-theory-attribute-to-create-parameterised-tests-with-inlinedata-)to run a test.
For every value, the test is executed and the value is avialable in the test.
It would be intresting to have that feature in tracetest.
Suppose to test various endpoint for there healthy state.

Something like this:

```
type: Test
spec:
  id: core-heatlh
  name: Core Health
  description: Check if core API is healthy
  trigger:
    type: http
    inlineData: {
       url: ['core.integration','admin.integration']
    }
    httpRequest:
      url: http://{url}/hc
      method: GET
      headers:
      - key: Content-Type
        value: application/json
  specs:
  - selector: span[tracetest.span.type="http" name="/hc" http.target="/hc" http.method="GET"]
    assertions:
    - attr:http.status_code  =  200
```

and this will result in to tests executed

**Comment by kdhamric** [comment]
We will definitely want to support variable data in tests, and doing test runs with particular sets. Most test tools will take some form of a CSV file and execute a run for each line in the test. We are 75-80% there in Tracetest with the ability to define variables via environmental variables and use them in tests.

Today, the easiest work around would be a script to define a variable (url in your example) in an environmental variable, run a test via the CLI, and then alter the environment and run it again. Having an example of this would be useful - I am going to ask one of the devs to provide one.

**Comment by schoren** [comment]
Hi @BartNetJS, I was working on an example script for this, but I hit a bug in our CLI that we need to fix before this can be done. I'll let you know as soon as it's released, and right after that I'll publish the example script.
Sorry this is taking longer than expected :(

**Comment by schoren** [comment]
Hi @BartNetJS, sorry for the delay in this. I have opened a PR with an example of how to do table driven tests with tracetest: https://github.com/kubeshop/tracetest/pull/2618

The relevant part is the script: https://github.com/kubeshop/tracetest/blob/18cb4d3acceaa5cdffbed35040f07e31da2d708d/examples/table-driven-test/table-test.bash

To run it, you need to pass a test definition file and a csv data (a.k.a the table):

```
./table-test.bash the-test.yaml data.csv
```

it will create a new environment for each of the CSV lines. It will use the header row for the keys, so for example, this csv:

```csv
pokeid,someValue
1,poke-1
2,poke-2
```

becomes this 2 envs:
```
---
type: Environment
spec:
  id: nply2h84g-iteration-2
  name: nply2H84g-iteration-2
  description: ""
  values:
  - key: pokeid
    value: "2"
  - key: someValue
    value: poke-2

---
type: Environment
spec:
  id: nply2h84g-iteration-1
  name: nply2H84g-iteration-1
  description: ""
  values:
  - key: pokeid
    value: "1"
  - key: someValue
    value: poke-1
```

I hope this helps you. Let me know if you need any help setting this up, or were expecting something different!
