### ISSUE TITLE
environment file is not correctly processed when running test on CLI

### ISSUE THREAD

**Issue by schoren** [kubeshop/tracetest#2548]
**Describe the bug**
I am trying to run a test passing an environment yaml file as an argument:

```
tracetest test run --definition test.yaml --environment /var/folders/dt/16tb9xfj1m181n7b9xyx7w240000gn/T/tmp.OEcOiGZN --wait-for-result
```

I expect the command to run the test with the values from the file, but instead I get a prompt for the values:

![Screenshot 2023-05-16 at 11 18 36](https://github.com/kubeshop/tracetest/assets/314548/56714cb6-144c-43f5-909f-2533b1e18070)

My env file looks like this:

```yaml
# /var/folders/dt/16tb9xfj1m181n7b9xyx7w240000gn/T/tmp.OEcOiGZN
type: Environment
spec:
  name: nply2H84g-iteration-1
  values:
  - key: "pokeid"
    value: "1"
  - key: "someValue"
    value: "poke-1"
```

The test looks like this:
```yaml
type: Test
spec:
  id: nply2H84g
  name: ITERATION TEST
  description: Import a Pokemon
  trigger:
    type: http
    httpRequest:
      url: http://demo-pokemon-api.demo/pokemon/import
      method: POST
      headers:
      - key: Content-Type
        value: application/json
      - key: X-Some-Header
        value: ${env:someValue}
      body: '{"id":${env:pokeid}}'
```

**To Reproduce**
1. try to run a test that has env vars from the CLI 
2. pass the `--environment` flag pointing to a valid environment definition file

**Expected behavior**
I expect to see the test running using the environment values from the passed file.

**Additional context**

CLI version: v0.11.8
Server version: v0.11.8
