### ISSUE TITLE
Deploy scheduled tests with a helm chart

### ISSUE THREAD

**Issue by BartNetJS** [kubeshop/tracetest#2568]
I like to deploy tracetest's yaml files as part of a CD pipeline.
Currently the tracetest server is already deployed by a helm chart via a github action.
The github action dedicated agent doesn't have direct access to the tracetest server running in AKS.
So **tracetest configure -g --endpoint http://...** is not an option to get the test files deployed to the tracetest server.

**Comment by adnanrahic** [comment]
Hey @BartNetJS ! Thanks for opening this issue. It's a great idea to enable scheduling tests.
We have this particular enhancement in our backlog. We'll get back to you on this once we discuss it in our next team meeting. 😄

**Comment by BartNetJS** [comment]
Great @adnanrahic !

Do you have a workaround or idea how I can achieve the following today?

CICD into an environment (in my case azure AKS Dev, tst, acc and prd)
Run tracetests as part of the CD
As noted above, the github agent doesn't have direct access to the tracetest server.
So one option is to deploy the tests via helm charts and get it executed.
And report the result back

One idea is:
Start a job as part of the helm install/upgrade:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job
spec:
  template:
    spec:
      containers:
      - name: job
        image: your-image
        command: ["command-to-launch-tests"]
      restartPolicy: Never
  backoffLimit: 4
```

Wait for the job to complete:
`kubectl wait --for=condition=complete job/my-job`

Get the state of the job:
`kubectl get job my-job -o json | jq -r '.status.conditions[] | select(.type=="Complete") | .status'`

And read the logs:

`kubectl logs job/my-job`

And validate the result

Or do you have another idea?
