### ISSUE TITLE
[CLI Improvements] Migrate Tests to resource manager architecture - GET /tests/{id} - CLI

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#2669]
This task is part of the test migration for the GET /tests/{id} endpoint

### Acceptance criteria

**AC1**
As a user using the CLI
I should be able to use the resource verb `get` to get a test from the server
And the output should be formatted depending on the flag I use

`tracetest get test --id [the id]` 

**Description:** Get a test by ID
**Required flags:** `--id`
**Optional Flags:** none
**Pretty Output Example:**

| ID | Name | Version | Trigger Type | Runs | Last Run Time | Last Run Successes | Last Run Fails | URL |
|---|---|---|---|---|---|---|---|---|
| WZGNTOBVg | Pokeshop - List | 1 | http | 5 | 2hs ago | 1 | 0 | http://localhost:11633/test/WZGNTOBVg

**JSON Output Example:**
```json
{
	"type": "Test",
	"spec": {
		"id": "uivSWYf4g",
		"name": "Pokeshop - List",
		"description": "Get a Pokemon",
		"version": 1,
		"createdAt": "2023-03-27T20:08:14.171787Z",
		"serviceUnderTest": {
			"triggerType": "http",
			"triggerSettings": {
				"http": {
					"url": "http://demo-pokemon-api.demo.svc.cluster.local/not-exists",
					"method": "GET",
					"headers": [{
						"key": "Content-Type",
						"value": "application/json"
					}]
				}
			}
		},
		"specs": {
			"specs": [{
				"name": "",
				"selector": {
					"query": "span[tracetest.span.type=\"general\" name=\"Tracetest trigger\"]",
					"structure": [{
						"filters": [{
								"property": "tracetest.span.type",
								"operator": "=",
								"value": "general"
							},
							{
								"property": "name",
								"operator": "=",
								"value": "Tracetest trigger"
							}
						]
					}]
				},
				"assertions": [
					"attr:tracetest.response.status = 200"
				]
			}]
		},
		"summary": {
			"runs": 5,
			"lastRun": {
				"time": "2023-03-27T20:08:14.366933Z",
				"passes": 1
			}
		}
	}
}
```

**YAML Output example:**
```yaml
---
type: Test
spec:
  id: uivSWYf4g
  name: Pokeshop - List
  description: Get a Pokemon
  trigger:
    type: http
    http:
    	url: http://demo-pokemon-api.demo.svc.cluster.local/not-exists
      method: GET
      headers:
      - key: Content-Type
      value: application/json
  specs:
    - selector: span[tracetest.span.type="general" name="Tracetest trigger"]
      assertions:
      - attr:tracetest.response.status = 200
```
