### ISSUE TITLE
Applying demo resource with numeric IDs cause the API server to panic

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#2718]
**Describe the bug**

Applying this resource on the server (`tracetest apply demo --file my-demo.yaml`):

```yaml
type: Demo
spec:
  id: 1
  name: dev
  type: otelstore
  enabled: true
  opentelemetryStore:
    frontendEndpoint: http://dev-frontend:9000
    productCatalogEndpoint: http://dev-product:8081
    cartEndpoint: http://dev-cart:8082
    checkoutEndpoint: http://dev-checkout:8083

```

Makes our server to enter in panic state and crashes.
