### ISSUE TITLE
Applying new demo resource with fixed id gives error message

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#2719]
**Describe the bug**

When I try to apply a demo resource to our server with `tracetest apply demo --file my-demo.yaml`:

```yaml
type: Demo
spec:
  id: some-id
  name: dev
  type: otelstore
  enabled: true
  opentelemetryStore:
    frontendEndpoint: http://dev-frontend:9000
    productCatalogEndpoint: http://dev-product:8081
    cartEndpoint: http://dev-cart:8082
    checkoutEndpoint: http://dev-checkout:8083
```

Returns the following result:
```
Version
CLI: dev
Server: dev
✔️ Version match
        	            			
An error ocurred when executing the command
        	            	
demos id doesn't exist on server. Remove it from the definition file and try again
```

This behavior don't happen in other resources.
