### ISSUE TITLE
Analyzer provisioning crashes to `enabled` flag as false

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#2737]
**Describe the bug**

I've created a provision file like this:
```yaml
---
type: PollingProfile
spec:
  name: Default
  strategy: periodic
  default: true
  periodic:
    retryDelay: 5s
    timeout: 10m

---
type: DataStore
spec:
  name: Jaeger
  type: jaeger
  default: true
  jaeger:
    endpoint: jaeger:16685
    tls:
      insecure: true

---
type: Analyzer
spec:
  id: current
  name: Analyzer
  enabled: false
  minimumScore: 0
```

And created a container for tracetest on version `v0.11.13`. The provision step fails and we receive the following message on the database:
<img width="1320" alt="image" src="https://github.com/kubeshop/tracetest/assets/12397879/e3ef2edf-44b2-4b32-9649-0e461b100406">
