### ISSUE TITLE
Ui hung on detailed run and pathPrefix issue

### ISSUE THREAD

**Issue by BartNetJS** [kubeshop/tracetest#2968]
I've updated to the latest version V0.13.0
When I click on a detailed run, the page is not responsive anymore.
I got
![image](https://github.com/kubeshop/tracetest/assets/4865355/5e3def65-8796-465d-9a44-b610d7d1a6ea)
If I wait long enough I got a response back

Also pathPrefix is not working for the liveness route, it return 404. I see in the yaml that liveness is on the prefix, but got 404 in the kubenretes events.
See also an old issue here https://github.com/kubeshop/tracetest/issues/2907

**Comment by jorgeepc** [comment]
Hey @BartNetJS thank you for opening this issue. I am not able to reproduce the problem. Could you share more details about your `test`? The test definition file could help. Also, I am curious about the size of the response body of your trigger and the number of spans.

**Comment by BartNetJS** [comment]
It's a very simple test:

```
type: Test
spec:
  id: integration-das-liveness
  name: DAS
  trigger:
    type: http
    httpRequest:
      url: http://someapiroute....
      method: GET
      headers:
      - key: Content-Type
        value: application/json
  specs:
  - selector: span[tracetest.span.type="general" name="Tracetest trigger"]
    assertions:
    - attr:tracetest.response.status = 200
```

First try:

![image](https://github.com/kubeshop/tracetest/assets/4865355/7b8c05d7-850a-4645-9dbd-192a77453258)

Past the url direct in another browser (chrome):

![image](https://github.com/kubeshop/tracetest/assets/4865355/5ec5e9b9-37b7-4077-ba7b-a7ae1d77fc0a)

Also tested in incognito: same result

Here i got a response after a long time:
![image](https://github.com/kubeshop/tracetest/assets/4865355/17e39c77-7672-4780-823e-095cd1d91b62)

Somethimes i got this:

![image](https://github.com/kubeshop/tracetest/assets/4865355/2bbaab00-e6c6-44f6-b1ac-42f51af4d6a7)

Logs from server seams ok

![image](https://github.com/kubeshop/tracetest/assets/4865355/df978873-1bc3-431a-bc16-0cc44c21fcea)
