### ISSUE TITLE
document local environment variables injection in CLI

### ISSUE THREAD

**Issue by mathnogueira** [kubeshop/tracetest#2994]
**Describe the enhancement you'd like to see**
Our CLI is able to replace values into the definition file when you run `tracetest run test`. For example:

```yaml
type: Test
spec:
  name: POST import pokemon
  description: Import a pokemon using its ID
  trigger:
    type: http
    httpRequest:
      url: http://pokemon-demo.tracetest.io/pokemon/import
      method: POST
      headers:
      - key: Content-Type
        value: application/json
      authentication:
        type: apiKey
        apiKey:
          key: X-Key
          # This is a reference to a local environment variable
          # This is different than when we reference environments 
          # (soon-to-be variablesets), which we prefix with `env:`
          value: ${POKEMON_APP_API_KEY}
          in: header
      body: '{ "id": 52 }'
```

Our CLI will detect the placeholder `${VAR_NAME}` and replace the string `${VAR_NAME}` with the content
of the environment variable with the same name.
