### ISSUE TITLE
Stops displaying page without imported id

### ISSUE THREAD

**Issue by dimonioi4** [kubeshop/tracetest#3746]
When running a test(test suite) through the CLI without the ID 
example
 ```
type: Test
spec:
  name: POST_getCollectionOfUsers
  description: Import a description
  trigger:
    type: http
```
UI error:
Something went wrong!
TypeError: Cannot read properties of undefined (reading 'id')

No possibility to fail in test suite(testran)

**To Reproduce**
1. Run test suite with CLI without the ID 
2. go to page Test suites
3. click run information

**Expected behavior**
opens a page with information on running tests

**Screenshots**
<img width="1778" alt="errorTrace" src="https://github.com/kubeshop/tracetest/assets/58983231/71bd011b-6248-4f0c-a37a-978d044077dc">
**Browser (please complete the following information):**
Chrome.
v 122.0.6261.129, (x86_64)
Tracetest v0.15.3(open source version)
