### ISSUE TITLE
Metrics server error on startup when an user is not setting metrics collection

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#3858]
When a user starts a Tracetest server without metrics section properly configured:
```yaml
telemetry:
      exporters:
        collector:
          exporter:
            collector: # here
              endpoint: address-to-otel-collector:4317
            type: collector
          metricsReaderInterval: 60s # and here
          serviceName: tracetest
```

Our server starts to raise the following error at startup:
```
failed to upload metrics: rpc error: code = Unimplemented desc = unknown service opentelemetry.proto.collector.metrics.v1.MetricsService
segment 2024/05/17 14:29:00 ERROR: 1 messages dropped because they failed to be sent after 10 attempts
```
