### ISSUE TITLE
Testing Observability Pipeline

### ISSUE THREAD

**Issue by francisan** [kubeshop/tracetest#3997]
Hi,

How I can test below pipeline using some sample payload. Want to test/ensure connector routes the request to corresponding pipeline based on the field 'name'.

```yaml
receivers:
  webhookevent:

      endpoint: 0.0.0.0:1111
      path: /get/info

processors:
  transform/tr:

       error_mode: ignore
       log_statements:
        - context: log
          statements:
           - set(body, ParseJSON(body)) where body != nil
           - set(resource.attributes["name"], body["name"])
         
connectors:
  routing :
      table:
        - statement: route() where attributes["name"] == "abc"
           pipelines:
            - logs/abc
        - statement: route() where attributes["name"] == "xyz"
           pipelines:
            - logs/xyz            
     
exporters:
 logging:
   loglevel: debug



service:
  pipelines:

  logs/receivers:
    receivers: [webhookevent]
    processors: [transform/tr]
    exporters: [routing,logging]
    
  logs/abc:
    receivers: [routing]
    processors: []
    exporters: [logging]
    
  logs/xyz:
    receivers: [routing]
    processors: []
    exporters: [logging]

```

Want to build something as shown below. Any existing test frameworks available?

```yaml
type: Test
spec:
  id: 19L__G7IR
  name: Call API
  trigger:
    type: http
    httpRequest:
      url: http://host.docker.internal:1111/get/info
      method: POST
      headers:
      - key: Content-Type
        value: application/json
  specs:
 
    assertions:
    - attr:http.status_code  =  200
```

**Comment by danielbdias** [comment]
hi @francisan , how are you?

Are you planning to use OTel Collector to test the routing? As far as I see in the configurations, you are testing only with logs.

You can do with Tracetest, in a mixed approach, by running a test that will trigger an HTTP endpoint and validating its response, like this example:

```yaml
type: Test
spec:
  id: PrLoRxqIg
  name: Http Bin test
  trigger:
    type: http
    httpRequest:
      method: GET
      url: https://httpbin.org/get?hello=world
      headers:
      - key: Content-Type
        value: application/json
  skipTraceCollection: true
```

Then, manually inspect the OTel Collector logs to see if they are working.

Another option is to make your webhook emit traces and then validate it against a Tracing Backend.
