### ISSUE TITLE
CLI doesn't support quote escaping in assertions

### ISSUE THREAD

**Issue by schoren** [kubeshop/tracetest#735]
I'm trying to run this file:

```yaml
name: Tests List
description: List all available tests
trigger:
  type: http
  http_request:
    url: ${TARGET_URL}/api/tests
    method: GET
    headers:
    - key: Content-Type
      value: application/json
testDefinition:
- selector: span[name="GET /api/tests" type="http"]
  assertions:
  - tracetest.span.duration <= 500
  - tracetest.response.status = 200
  - tracetest.response.body contains "\"id\":\"${TEST_ID}\""
```

with this command: `TEST_ID="asd" tracetest test run -d test.yaml` and get the following error:

```
{"level":"error","ts":1655246741.2517319,"msg":"failed to run test","error":"could not run definition: could not create test from definition: could not convert test definition: could not parse assertion (tracetest.response.body contains \"\\\"id\\\":\\\"asd\\\"\"): 1:39: invalid input text \"\\\\\\\":\\\\\\\"asd\\\\\\\"\\\"\""}
```

It works correctly with this definition:
```yaml
name: Tests List
description: List all available tests
trigger:
  type: http
  http_request:
    url: ${TARGET_URL}/api/tests
    method: GET
    headers:
    - key: Content-Type
      value: application/json
testDefinition:
- selector: span[name="GET /api/tests" type="http"]
  assertions:
  - tracetest.span.duration <= 500
  - tracetest.response.status = 200
  - tracetest.response.body contains "${TEST_ID}"
```

It also doesn't work if I use single quote(`'`) instead of double quote (`"`)
