### ISSUE TITLE
Add ability to assert on time from start of test

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#767]
We currently have a tracetest.span.duration so we can assert against the length of a span.  This is useful when we want to ensure a process does not last longer than a certain amount of time.  There is a similar need:

As a User,
I want to make sure a particular process occurs within a certain time frame from the beginning of a test
So I can confirm that the speed of a process is staying within a particular maximum.

Example:
 - We have an async process that throws a message on a queue and returns.  A downstream process picks it up, and inserts a record in a database.  We want to ensure that write to the database happens in less than 2 seconds from the original call.
 
 Proposal:
 Add two computed fields to each span:
 - tracetest.span.triggerTimeMinusSpanStart
 - tracetest.span.triggerTimeMinusSpanEnd
 
 I hate these names - feel free to improve.
 
 For discussion purposes, but not as part of this issue:  We have #707 & #719 to add ability to specify an ancestor in a selector.  A similar use would (could?) be to specify the time from the ancestor to this span, and to be able to use it to set assertions.  Example: We have a long process, lots of stuff happening.  When I get in a certain area of the system, I want to ensure that a particular action occurs within 350 ms of a prior action.  In this case, I could specify an ancestor to the span I am selecting.  The system would add a couple computed fields, named tracetest.span.ancestorEndTimeMinusSpanStart and tracetest.span.ancestorTimeMinusSpanEnd.  DO NOT want to implement this... just wanted to mention it and get any thoughts.  We really need expressions at some point where we could have an attribute under test of 'span.startTime - test.startTime < 500 ms or span.EndTime - ancestor.StartTime < 100ms.

**Comment by mathnogueira** [comment]
Instead of using `tracetest.span` we might have another class of tracetest attributes, such as:

`tracetest.duration.sinceTrigger.start` and `tracetest.duration.sinceTrigger.end` (still not good names).

Another possibility could be enabling expressions on the right side of the assert operation. So, we could have assertions like:

```
span.startTime < tracetest.execution.startTime + 500ms
```

In the future (waaaay in the future), we could even enable function calls in assertions:
```
span.startTime < parent(this, `span[name="my-parent-span"]`).endTime + 1s
```

**Comment by mathnogueira** [comment]
Today we can achieve this with [outputs](https://docs.tracetest.io/cli/creating-tests/#outputs) and [expressions](https://docs.tracetest.io/concepts/expressions/).

Example:

```yaml
specs:
  - selector: span[name = "my last operation"
    assertions:
      # takes less than 1s to run operation since the message was read from the queue
      - attr:tracetest.span.endTime < env:GET_MESSAGE_FROM_QUEUE_TIMESTAMP + 1s
outputs:
  - name: GET_MESSAGE_FROM_QUEUE_TIMESTAMP
    selector: span[name = "get message from queue"]
    value: attr:tracetest.span.startTime  
```

This probably can be closed, @kdhamric.
