### ISSUE TITLE
Update the FE to support the new structured selectors

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#779]
The Backend team just updated their models that include the selector string and now it looks like this:

```
- selector:
              query: span[tracetest.span.type="http"]
              structure:
                - filters:
                  - property: tracetest.span.type
                    operator: '='
                    value: http
```

![Image](https://user-images.githubusercontent.com/11051031/174842149-3423ea69-2ad1-4bd3-994e-f4199b42f803.png)

We need to update the FE code to use this new structure rather than applying some regex rules to split the string selector.
