### ISSUE TITLE
support span outputs

### ISSUE THREAD

**Issue by mathnogueira** [kubeshop/tracetest#824]
**Is your feature request related to a problem? Please describe.**

When testing some applications, we might need to cross-check information from two or more different spans. At the current version, this is impossible, even if we had #782 implemented.

An example would be a test to ensure that e-commerce is capable of selling a product. I would expect that when purchasing a set of products, the operation would do:

* Check if the product has stock available
* Charge credit card
* Create a shipping ticket
* Reduce the amount of available stock of the products
* Check if product stock is correct after purchase (This is not possible because I can't know how many products I had in stock when I checked the stock in the first step)

**Describe the solution you'd like**

A way of exporting new variables that can be used in assertions of other spans.

```yaml
testDefinition:
- selector: span[name = "Check product stock"]:first
  export:
  - name: "product.stock"  # to access the exported value, you would reference tracetest.exported.<name>
    value: product_api.response.product_stock

- selector: span[name = "Purchase product"]
  export:
  - name: "product.bought_quantity"
    value: product_api.request.amount
  assertions:
  - tracetest.selected_spans.count = 1
  - product_api.response.status = 200

- selector: span[name = "Check product stock"]:last
  assertions:
  - product_api.response.product_stock = tracetest.exported.product.stock - tracetest.exported.product_bought_quantity
```      

**Additional context**
This requires #782 to be implemented to be effective.
