### ISSUE TITLE
Proposal: Tests organization and grouping

### ISSUE THREAD

**Issue by schoren** [kubeshop/tracetest#951]
## Problem
We need a way to group tests so they can be run as a single unit. Some tests will be able to run on its own, but others will require a specific run sequence. A possible solution would be to group sequences in "transactions", and have "suites" that can contains tests and sequences.

### Transactions
We can implement "transactions". A Transaction is a defined sequence of tests. A Transaction cannot be parallelized, but multiple transactions can be run in parallel.

### Suites
A suite is a group of Tests and Transactions, where each can be run in parallel.

## How it works
Transactions and Suites works independent from tests and vice-versa. Tests can exists without belonging to any Transaction or Suite, and they can also belong to more than one Transaction or Suite.

Transaction example:
```yaml
# transactions/test-delete-cart.yaml
transaction:
  id: 97d63b49-bd51-4dda-be37-603faad0fa68
  name: Test Delete Cart
  tests:
  - ./tests/login.yaml # tests can reference local files
  - a3cdd83c-4f67-454a-bec3-fbdc9b0b0c67 # or by id
  # - ...
```
Each of the `tests` are run in the exact order as described by the file.

Suite example:

```yaml
# suites/cart.yaml
suite:
  name: Shopping flow
  tests:
  - tests/login.yaml # tests can reference local files
  - a3cdd83c-4f67-454a-bec3-fbdc9b0b0c67 # or by id
  transactions:
  - transactions/test-delete-cart.yaml 
  - 19e865a2-55eb-4e89-8a75-ea3353dace34
```
This file would result in 4 concurrent tests, one for each defined tests, and one for each transaction. Each transaction executes its tests in the defined sequence.

## Usage
Both the CLI and the UI should expose ways to run tests, suites and transactions.
